baseURL = "https://www.afeather.art/"
languageCode = "en-us"
title = "A Feather's Gallery"
theme = "gallery"
disableKinds = ["taxonomy", "term"]


[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

# 图片处理配置：你可以调整质量等
[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription"
